apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 60m
  chart:
    spec:
      chart: podinfo
      version: "7.0.4" # automatically upgrade to the latest version
      interval: 5m # scan the Helm repository every five minutes
      sourceRef:
        kind: HelmRepository
        name: podinfo
      verify:
        provider: cosign
        matchOIDCIdentity:
          - issuer: "^https://token.actions.githubusercontent.com$"
            subject: "^https://github.com/aryan9600/podinfo.*$"
  test:
    enable: true # run tests on upgrades
