---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: podinfo
spec:
  type: "oci"
  interval: 5m0s
  url: oci://fluxkubecon.azurecr.io/charts
  provider: azure
